### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jaicab** [cssanimation/posts#1]
Hey @donovanh, great resource. I'm thinking on translating every single article into Spanish, should I email you as you say on the README or would it be better if I sent you a PR?

**Comment by almakdad** [comment]
Hi @jaicab My name is Mac. I'm the founder of Native. @donovanh is using Native to help collect and publish translations. If you're still interested in translating, please click on the translate button in any of his articles (see below). Let me know if you have any questions.

<img width="320" alt="screen shot 2015-12-03 at 4 18 32 pm" src="https://cloud.githubusercontent.com/assets/131805/11578362/9c1f14da-99d9-11e5-8761-f3e9cf6b6397.png">

**Comment by donovanh** [comment]
@jaicab sorry to miss this - my notifications were off and I didn't check this repo. I'd love Spanish translations! Please to use the Native button to get started, it allows for multiple collaborators, and manages the translations nicely.

**Comment by jaicab** [comment]
Great! I'll use native, no worries. Thanks @donovanh and @almakdad :)
